compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 8
mixed_precision: bf16
deepspeed_config:
  zero_stage: 2
  offload_optimizer_device: 'cpu'
  offload_param_device: 'cpu'
  gradient_accumulation_steps: 1
